name:                volpano-smith
version:             0.1.0.0
github:              "madgen/volpano-smith"
license:             BSD3
author:              "Mistral Contrastin"
maintainer:          "madgenhetic@gmail.com"
copyright:           "2021 Mistral Contrastin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/madgen/volpano-smith#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-typelits-extra >= 0.4 && < 0.5

library:
  source-dirs: src
  ghc-options: -Wall
